### ISSUE TITLE
Settings window closes automatically by any activity outside the window

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#126]
Settings window or probably similar windows close automatically without pressing the x (or escape) button when any activity is detected outside the window, for example when alt-tab out of the program or minimizing the program.

**Comment by maestrith** [comment]
I may not be understanding what you mean...
![capture](https://user-images.githubusercontent.com/2114637/29418740-2a8ad19a-833b-11e7-9cf1-a49b9d1f8845.gif)

**Comment by ali80** [comment]
well that's odd, you understood correctly but can't reproduce it.
in the uploaded video first I used the minimize button and second and third time used alt-tab
[Video_2017-08-17_234100.zip](https://github.com/maestrith/AHK-Studio/files/1232343/Video_2017-08-17_234100.zip)
can you maximize ahk-studio, sometimes when it is not maximized it works fine!

**Comment by maestrith** [comment]
OH...odd.  Thank you for that video.  Not sure what the difference is but when I follow your sequence of events then it does reproduce.  I'll have to see what I can do to fix that.  I understand why and can make it so that the main window is the parent and that _should_ solve it for most of the windows.

**Comment by ali80** [comment]
Fixed, thanks for the fast fix.
