### ISSUE TITLE
AHK-Studio startup problem when non-english keyboard is active

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#127]
If at program startup, the language is ENG, everything works fine, but if not, the program won't launch properly.
the problem is kinda the same with sciTE4Autohotkey but at least it gives clear error message which tells what is wrong and also the program launches after that (though after program launch if I change the keyboard layout, the shortcuts such as ^i still work, so why the error message in the first place!)
[Video_2017-08-18_163148.zip](https://github.com/maestrith/AHK-Studio/files/1234365/Video_2017-08-18_163148.zip)

**Comment by maestrith** [comment]
what in the world?! Thanks once again for the video!

**Comment by ali80** [comment]
thanks for the fast response and fix,
well the startup issue is fixed ... partially :)
now if the program starts on non-english keyboard and then the keyboard is changed to ENG, all the internal program shortcuts stop working(e.g. alt+R opens format menu instead of running the script)

**Comment by maestrith** [comment]
I'm in the process of trying to figure it out, and I can get Studio to detect the keyboard layout when it gets focus, but the problem is that when you change the languages in the systray it does not take the focus away from Studio :(
`#SingleInstance,Force
OnMessage(0x51,"LanguageChange")
;Gui,Add,Edit,w500 h500 ;run the first time with this commented out, then the next time with it in and then change the languages
Gui,Show,w500 h500
return
f1::
return
GuiClose:
GuiEscape:
ExitApp
return
LanguageChange(a*){
	m(a.1)
}`

**Comment by ali80** [comment]
well my circle of knowledge includes finding bugs and not fixing them :D , but that doesn't stop me from trying :), I ran your script, in first case it always detected language change whether losing focus or not, it second case, in never detected any language change.
I tested the default autohotkey gui (i don't know what its called, the one that launches when you double click on tray icon) it doesn't seem to have this problem and it's shortcuts always work whatever the input language is. I don't have the knowledge to help you but maybe that could.

**Comment by akaleeroy** [comment]
> `OnMessage(0x51,"LanguageChange")`

@maestrith According to this thread that won't work by itself: 
[Getting the InputLanguageChange message - Ask for Help - AutoHotkey Community](https://autohotkey.com/board/topic/29254-getting-the-inputlanguagechange-message/)
